### ISSUE TITLE
题面题解榜单上传

### ISSUE THREAD

**Issue by CurryWOE** [xcpcio/docs#15]
想上传2023四川省赛的题面题解榜单，没有在仓库中发现可以放文件的地方，请问怎么上传？另外榜单只有终榜可以吗，是参赛者来做一点小小的贡献

**Comment by Dup4** [comment]
欢迎欢迎！

https://github.com/XCPCIO/upload-file/tree/main/upload-file/provincial-contest

文件可以提个 PR 上传到这个仓库

然后在本仓库下提个 RP 新建一个页面，来放置四川省赛相关的信息

https://github.com/XCPCIO/XCPCIO/blob/main/docs/info/provincial-contest/2022/hbcpc.md?plain=1#L3-L4

如果要引用文件的链接的话，参考这里这个写法

另外，想问一下，榜单是什么格式的？

**Comment by CurryWOE** [comment]
主办方只提供了pdf的终榜

**Comment by Dup4** [comment]
pdf 的话，那要不就上传到 `upload-file` 这个 repo 吧？

目前也没啥好的办法把它解析出来然后搞到 <https://board.xcpcio.com> 上

**Comment by Dup4** [comment]
现在看上去应该一切正常了

Thank you!
